services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

volumes:
  pg-data:
